### PR TITLE
Add polling time configuration

### PR DESCRIPTION
**Pull request by vkareh**
This adds a new combo box for selecting the polling time. I've added some common values that are typical of monitor refresh rates, for lack of a better list. I've also defaulted it to 120, as that seems to be a good compromise between performance and choppiness, but happy to change the value and/or list of values.

### CODE REVIEW

**Comment by stuartlangridge** [comment]
A couple of questions, if I may.

Firstly, can you talk about why it's a good idea to expose this directly to users? It feels like quite an "advanced" setting, and I am in general in favour of keeping magnus as small and simple as possible. I don't necessarily know why the refresh rate would need to be smoother? It will be quite intensive on lower-powered machines to refresh more often, and I don't know how much benefit there is; smoothness is nice, but it's not all that important, I don't think?

Secondly, I think the refresh rates for monitors (60, 120, 144, and so on) are in Hz; that is, a 60Hz monitor doesn't refresh every 60 milliseconds, but 60 times per second or every _16_ milliseconds. A 120Hz refresh rate is 1000/120, or every 8.3ms. I don't think we can sensibly match the refresh rate of a monitor; we'll hammer the machine into the ground trying to grab a screen section from the X server every 8 miliseconds. So even if having switchable refresh rates for this is a good idea, I don't think these are the correct refresh rates to choose. But, as above, I'm not sure that it's a useful idea; having magnus refresh four times a second seems tolerably smooth to me and doesn't impact the machine all that much, and I don't know that the benefit obtained from making the rate switchable outweighs the confusion caused by putting the switcher in such an important place in the user interface.

But, I'm not an accessibility expert. So, if there are reasons I don't know why this would be important, or why the anticipated users of magnus are likely to really want this feature to be switchable all the time, then I'm happy to listen.

**Comment by vkareh** [comment]
@stuartlangridge, no worries, these are good questions - I chose refresh rate numbers arbitrarily, not even thinking about the Hz vs ms issue, which you're entirely correct about: the math doesn't work that way :stuck_out_tongue_closed_eyes: 

It was literally just playing with the numbers and seeing which ones felt better. 50ms was the lowest I could go before my computer "felt it". 60ms was a very smooth magnifying experience, 120ms was "ok", but usable.

In terms of accessiblity, I am not an expert, but this app is useful even without the a11y use-case in mind. Sometimes I want to zoom in on a photo/image I'm working on, or some website I'm developing, and having a smooth rendering makes a huge difference for me.

Maybe this could be entirely hidden from the user and just provide it in the config file (or as a cmdline arg?). I'm okay tossing this change, it was a quick hack to improve my personal use case. :slightly_smiling_face:

**Comment by stuartlangridge** [comment]
I've just pushed a change which allows you to run magnus as `magnus --refresh-interval=60`, which should hopefully handle your use case fine, so I'll close this pull request; thank you for the feedback!

**Comment by vkareh** [comment]
Yes! This works really well for me. Thanks!

**Pull request closed without merging**
